/* File generated by gen_cfile.py. Should not be modified. */

#ifndef __canfestival_master_H
#define __canfestival_master_H



#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data Master_Data;
extern INTEGER8 mode1;		/* Mapped at index 0x2000, subindex 0x00*/
extern INTEGER32 velocity1;		/* Mapped at index 0x2001, subindex 0x00*/
extern INTEGER16 torque1;		/* Mapped at index 0x2002, subindex 0x00*/
extern INTEGER8 mode2;		/* Mapped at index 0x2003, subindex 0x00*/
extern INTEGER32 velocity2;		/* Mapped at index 0x2004, subindex 0x00*/
extern INTEGER16 torque2;		/* Mapped at index 0x2005, subindex 0x00*/
extern INTEGER16 rec_torque1;		/* Mapped at index 0x2006, subindex 0x00*/
extern INTEGER16 rec_torque2;		/* Mapped at index 0x2007, subindex 0x00*/

#endif // MASTER_H


